#pragma once
#define SCREEN_WIDTH		    800
#define SCREEN_HEIGHT		    600
#define SCREEN_FPS			    60
#define SCREEN_MS_BY_FPS	    1000 / 60

#define STARTING_ROAD_WIDTH		400
							    
#define CAR_STARTING_X		    -1000
#define CAR_STARTING_Y		    -1000
#define CAR_WIDTH			    60
#define CAR_HEIGHT			    60
#define CAR_HORIZONTAL_SPEED    4
#define CAR_VERTICAL_SPEED	    6

#define PLAYER_STARTING_X		SCREEN_WIDTH / 2
#define PLAYER_STARTING_Y		SCREEN_HEIGHT / 2
#define PLAYER_HORIZONTAL_SPEED 8
#define PLAYER_VERTICAL_SPEED	5
#define PLAYER_NEW_CAR			5000

#define MAX_BULLETS 1000
#define BULLET_WIDTH 5
#define BULLET_HEIGHT 20
#define BULLET_SPEED 5

#define MAX_ENEMIES_AT_ONCE		3
#define MAX_CIVILS_AT_ONCE		3
#define ENEMIES_SPAWNPOINT		100
#define CIVILS_SPAWNPOINT		100

#define LOAD_GAME_WINDOW_WIDTH  450
#define LOAD_GAME_WINDOW_HEIGHT 450
#define LOAD_GAME_STARTING_X	(SCREEN_WIDTH - LOAD_GAME_WINDOW_WIDTH) / 2
#define LOAD_GAME_STARTING_Y	(SCREEN_HEIGHT - LOAD_GAME_WINDOW_HEIGHT) / 2

#define MAX_SAVED_GAMES			20
#define MAX_FILE_LENGTH			128
#define SAVED_GAMES_FOLDER_NAME "savedGames/"
